#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_ICP10125_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_ICP10125_H_

#include <zephyr/drivers/sensor.h>

enum sensor_channel_icp10125 {
	SENSOR_CHAN_RAW_AMBIENT_TEMP = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_RAW_PRESS,
	SENSOR_CHAN_OTP_VAL1,
	SENSOR_CHAN_OTP_VAL2,
};

#endif /* ZEPHYR_INCLUDE_DRIVERS_SENSOR_ICP10125_H_ */
